# Note: You can use any Debian/Ubuntu based image you want. 
FROM gocv/opencv:4.10.0-static

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>